import "./globals.css";

export const metadata = {
  title: "Portfolio | Built with Devfoliox",
  description: "A professional developer portfolio generated by Devfoliox.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full antialiased" suppressHydrationWarning>
      <body
        className="min-h-full flex flex-col font-serif"
        suppressHydrationWarning
      >
        {children}
        <a
          href="https://github.com/christian-fx/Devfoliox"
          target="_blank"
          rel="noopener noreferrer"
          className="text-gray-900 font-medium hover:text-blue-600 transition-colors"
        >
          Built with Devfoliox
        </a>
      </body>
    </html>
  );
}
