import "./globals.css";

export const metadata = {
  title: "Modern Portfolio | Built with Devfoliox",
  description: "A high-performance developer portfolio generated by Devfoliox.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full antialiased" suppressHydrationWarning>
      <body
        className="min-h-full flex flex-col font-serif"
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
